DaisyMedia68/DaisyMedia68/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using DaisyMedia68.Business;
using DaisyMvc.Models;
using DaisyMvc.Models.ViewModels;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using Microsoft.WindowsAzure.Storage.RetryPolicies;
using Newtonsoft.Json;

namespace DaisyMvc.Controllers
{


    public class VideoController : Controller
    {

        private readonly string DIRPATH = System.Web.HttpContext.Current.Server.MapPath("~/Content/UploadedFiles/");


        // GET: Video
        //[Route("videos")]       todo - workout why this isnt working - i should be able to change the method name and still route to this from "video/videos"
        //[Authorize]
        //public ActionResult VideosViaApi()
        //{
        //    var results = HttpClientGetData();

        //    //todo move elsewhere and make VideosVm.Videos a collection of Video objects , not string as it currently is
        //    var vvm = new VideosVm { Videos = results };


        //    //return Content("You reached the Video/Videos Action Controller");
        //    return View(vvm);
        //}


        //GET
        [Authorize]
        public ActionResult Videos()
        {

            var results = Directory.GetFiles(DIRPATH);

            //debug
            TempData["getFileResults"] = "<script>alert(' file count: "+ results.Length +" ');</script>";

            var vvm = new VideosVm();
            vvm.Videos = new List<VideoFile>();

            int ctr = 0;
            foreach (var result in results)
            {
                VideoFile v = new VideoFile() { Id = ++ctr, Title = Path.GetFileName(result) };
                vvm.Videos.Add(v);
            }

            //return Content("You reached the Video/Videos Action Controller");
            return View(vvm);
        }



        //POST

        private string uploadedFilesPath = "~/Content/UploadedFiles";

        [HttpPost]
        public ContentResult MultiUpload(string id, string fileName)
        {
            // If writing files to file system, use WriteChunksToTempFolder and MergeTempFolderChunks (call from UploadComplete)


            //currently saving to file system   - this needs the MergeTemp... call in UploadComplete method
            WriteChunksToTempFolder(id, fileName);

            // If writing the file to blob storage we can do this in chunks too, using StreamWriteSizeInBytes
            AzureBlobStorageHandler absh =  WriteStreamToBlobInBytes(id, fileName);

            TempData = absh.DebugInfo;

            string msg = TempData["1"].ToString() + " : " + TempData["2"].ToString();

            return Content(msg);
            //return "done";
        }



        [HttpPost]
        public string UploadComplete(string fileName, string complete)
        {
            MergeTempFolderChunks(fileName, complete);
            return "success";
        }




        private AzureBlobStorageHandler WriteStreamToBlobInBytes(string id, string fileName)
        {
            // id   - needed ?

            AzureBlobStorageHandler absh = new AzureBlobStorageHandler();

            absh.UploadToBlobFromFile(fileName);

            return absh;

        }


        private void WriteChunksToTempFolder(string id, string fileName)
        {
            var chunkNumber = id;
            var chunks = Request.InputStream;
            string path = Server.MapPath(uploadedFilesPath + "/Temp");
            string newpath = Path.Combine(path, fileName + chunkNumber);
            using (FileStream fs = System.IO.File.Create(newpath))
            {
                byte[] bytes = new byte[AppValues.FileChunkSz];
                int bytesRead;
                while ((bytesRead = Request.InputStream.Read(bytes, 0, bytes.Length)) > 0)
                {
                    fs.Write(bytes, 0, bytesRead);
                }
            }
        }

        private void MergeTempFolderChunks(string fileName, string complete)
        {
            string tempPath = Server.MapPath(uploadedFilesPath + "/Temp");
            string videoPath = Server.MapPath(uploadedFilesPath);
            string newPath = Path.Combine(tempPath, fileName);
            if (complete == "1")
            {
                string[] filePaths =
                    Directory.GetFiles(tempPath)
                        .Where(p => p.Contains(fileName))
                        .OrderBy(p => Int32.Parse(p.Replace(fileName, "$").Split('$')[1]))
                        .ToArray();
                foreach (string filePath in filePaths)
                {
                    MergeFiles(newPath, filePath);
                }
            }
            System.IO.File.Move(Path.Combine(tempPath, fileName), Path.Combine(videoPath, fileName));
        }

        private static void MergeFiles(string file1, string file2)
        {
            FileStream fs1 = null;
            FileStream fs2 = null;
            try
            {
                fs1 = System.IO.File.Open(file1, FileMode.Append);
                fs2 = System.IO.File.Open(file2, FileMode.Open);
                byte[] fs2Content = new byte[fs2.Length];
                fs2.Read(fs2Content, 0, (int)fs2.Length);
                fs1.Write(fs2Content, 0, (int)fs2.Length);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message + " : " + ex.StackTrace);
            }
            finally
            {
                if (fs1 != null) fs1.Close();
                if (fs2 != null) fs2.Close();
                System.IO.File.Delete(file2);
            }
        }


        [HttpPost]
        public ActionResult UploadFiles2(HttpPostedFileBase file)
        {

            //stick it in a collection to pass to SaveFiles
            SaveFiles(new List<HttpPostedFileBase>() { file });

            //todo not sure where to go from here at the moment....
            return Content("file uploaded successfully");
        }




        [HttpPost]
        public ActionResult UploadFiles(IEnumerable<HttpPostedFileBase> files)
        {
            SaveFiles(files);

            return RedirectToAction("Videos");
        }

        //}
        public ActionResult DeleteFile(string filename)
        {
            string fullSavePath = DIRPATH + filename;
            System.IO.File.Delete(fullSavePath);

            return RedirectToAction("Videos");
        }


        private void SaveFiles(IEnumerable<HttpPostedFileBase> files)
        {
            foreach (var file in files)
            {
                // in case it has the path....
                string fname = Path.GetFileName(file.FileName);

                string fullSavePath = DIRPATH + fname;
                file.SaveAs(fullSavePath);
            }
        }


        ////[Route("videos")]       todo - workout why this isnt working - i should be able to change the method name and still route to this from "video/videos"
        //public ActionResult Videos(int id)
        //{

        //    var theFile = HttpClientGetFileExample(id);

        //    Response.Clear();
        //    Response.AddHeader("Content-Length", theFile.FileStream.Length.ToString());
        //    Response.AddHeader("Content-Disposition", "attachment; filename=FILENAME");
        //    Response.BinaryWrite(theFile.FileStream); 
        //    Response.Flush();
        //    Response.End();






        //    //todo move elsewhere and make VideosVm.Videos a collection of Video objects , not string as it currently is
        //    var vvm = new VideosVm { Videos = results };


        //    //return Content("You reached the Video/Videos Action Controller");
        //    return View(vvm);
        //}



        // GET: Video/Create
        public
        ActionResult Create()
        {
            //return View("PostFile");
            return View("DragDropFilePost");
        }

        // POST: Video/Create
        //[HttpPost]
        //public ActionResult Create(PostFileVm postedFile)
        //{
        //    //return Content("Posted.");
        //    //return View("PostFile");
        //    return View("DragDropFilePost");
        //}

        // POST: Video/Create
        [HttpPost]
        public ActionResult UploadFilesViaApi(IEnumerable<HttpPostedFileBase> files)
        {
            foreach (var file in files)
            {

                //bool ok = HttpPostToWebApi(file);
                //HttpPostToWebApi2(file);
                TryThisOne(file);


                //var filePath = Guid.NewGuid() + Path.GetExtension(file.FileName);

                ////todo - save em
                //file.SaveAs(Path.Combine(Server.MapPath("~/UploadedFiles"), filePath));
                ////Here you can write code for save this information in your database if you want
            }


            //todo not sure where to go from here at the moment....
            return Content("file uploaded successfully");
        }

        public ActionResult Open()
        {
            //check if we have the file locally




            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }


        //public class Video
        //{
        //    //[JsonProperty("Films")]
        //    public AFilm[] Films { get; set; }
        //}

        //public class AFilm
        //{
        //    [JsonProperty("id")]
        //    public int theId { get; set; }

        //    [JsonProperty("title")]
        //    public string theTitle { get; set; }

        //}

        //private async Task<HttpResponseMessage> postit(HttpPostedFileBase model)
        //{
        //    var r = new TResponse
        //    {

        //    }
        //    using (var apiResponse = await HttpClientPostToWebApi(model))
        //    {

DaisyMedia68/DaisyMedia68/Views/Video/DragDropFilePost.cshtml
@using DaisyMvc.Models
@{
    ViewBag.Title = "DragDropFilePost";
}

<div class="jumbotron jumboStyle1 bgImgLibrary1" , style="background-size: cover">
    <div class="row">
        <div class="col-sm-offset-10 col-sm-2 pull-right">

        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <h2>@*Drag & Drop file upload*@ </h2>
            <div id="dropArea" class="jumbotron seeThruBg">
                <span id="dropText">Drop File(s) Here Please..</span>
            </div>
            <h4>Uploaded files : </h4>
            <ul class="list-group" id="uploadList"></ul>

        </div>
        <div id="upload2" class="col-md-6">
            @*<h2>Basic File Upload</h2>*@

            <div id="VideoDiv">
                <label style="color: purple">Or, browse to find a file to post....</label>
                <span style="color: fuchsia">
                    <input type="file" id="fileInput" style="font-size: medium">
                </span><br />
                <input type="button" id="btnUpload" value="Add" class="btn-block seeThruBg" style="border: solid 2px fuchsia;" />
            </div>

            @*<span class="btn btn-block btn-primary">
                            Find a file <input  type="file" id="fileInput"  />
                        </span>
                        @*<input type="file" id="fileInput" style="background-color: fuchsia; font-size: 16px" /><br /><br />
                                    <input type="button" id="btnUpload" value="Add a file.." class="seeThruBtn" /><br /><br />

                </div>


                @using (Html.BeginForm("UploadFiles2",
                                "Video",
                                FormMethod.Post,
                                new { enctype = "multipart/form-data", @class = "seeThruBg" }))
                    {
                        <label for="file">Add a file...</label>
                        <input type="file" name="file" id="upload-file" /><br><br>
                        <input type="submit" id="btnUpload" value="Add now" class="seeThruBtn" />


                    }*@


        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div id="progressbar_container" style="width: 50%; height: 5px; position: relative; background-color: red; display: none">
                <div id="progressbar" style="width: 0%; height: 100%; position: absolute; background-color: greenyellow"></div>
                @*<span id="progressbar_label" style="position: absolute; left: 35%; top: 20%">Sending...</span>*@
                <span id="progressbar_label" style="color: greenyellow">Sending...</span>
            </div>
            @*<div class="col-md-offset-3 col-md-6">

                    <span class="btn btn-default btn-file">
                        MyText <input type="file">
                    </span>
                </div>*@

        </div>
    </div>

</div>  
@*@Html.Raw(TempData["1"])
@Html.Raw(TempData["2"])*@


<style>
    #dropText {
        color: purple;
        font-size: 30px;
    }

    #releaseText {
        color: blueviolet;
        font-size: 20px;
    }

    #dropArea {
        /*background:#b5b5b5;*/
        /*border:black dashed 1px;*/
        height: 250px;
        width: 450px;
        text-align: center;
        /*color:#fff;*/
        padding-top: 12px;
        /*background-color: yellow;*/
        color: yellow;
        border-style: solid;
        border-width: medium;
        border-color: purple;
    }

    .active-drop {
        /*background: greenyellow !important;*/
        border: solid 7px white !important;
        opacity: .5;
        color: black !important;
    }

    .inactive-drop {
        background-image: linear-gradient(rgba(255, 255, 255, 0.7), rgba(255, 255, 255, 0.7)), url('../../Content/Images/spongebob1.jpg');
    }
</style>

@section Scripts{


    <script src="~/Scripts/jquery.filedrop.js"></script>

    <script type="text/javascript">

        $(document)
            .ready(function() {

                var progressBarStart = function() {
                    $("#progressbar_container").show();
                }

                var progressBarUpdate = function(percentage) {
                    $('#progressbar_label').html(percentage + "%");
                    $("#progressbar").width(percentage + "%");
                }

                var progressBarComplete = function() {
                    $("#progressbar_container").fadeOut(500);
                }

                var file;

                $('#fileInput')
                    .change(function(e) {
                        file = e.target.files[0];
                    });

                var uploadCompleted = function() {
                    var formData = new FormData();
                    formData.append('fileName', file.name);
                    formData.append('completed', true);

                    var xhr2 = new XMLHttpRequest();
                    xhr2.onload = function() {
                        progressBarUpdate(100);
                        progressBarComplete();
                    }
                    xhr2.open("POST", "/Video/UploadComplete?fileName=" + file.name + "&complete=" + 1, true);
                    xhr2.send(formData);
                }

                var uploadFiles = function() {

                    var blob = file;
                    var bytesPerChunk = @AppValues.FileChunkSz;
                    var size = blob.size;

                    var start = 0;
                    var end = bytesPerChunk;
                    var completed = 0;
                    var count = size % bytesPerChunk == 0
                        ? size / bytesPerChunk
                        : Math.floor(size / bytesPerChunk) + 1;
                    var counter = 0;
                    progressBarStart();
                    multiUpload(count, counter, blob, completed, start, end, bytesPerChunk);

                }

                var multiUpload = function(count, counter, blob, completed, start, end, bytesPerChunk) {

                    //var debug = "count:" +
                    //    count +
                    //    " counter:" +
                    //    counter +
                    //    " blobsize:" +
                    //    blob.size +
                    //    " start:" +
                    //    start +
                    //    " end:" +
                    //    end +
                    //    " completed:"+completed;
                    //alert(debug);
                    counter = counter + 1;
                    if (counter <= count) {
                        var chunk = blob.slice(start, end);
                        var xhr = new XMLHttpRequest();
                        xhr.onload = function() {
                            start = end;
                            end = start + bytesPerChunk;
                            if (count == counter) {
                                uploadCompleted();
                            } else {
                                var percentage = (counter / count) * 100;
                                progressBarUpdate(percentage);
                                //alert("onload:"+counter);
                                multiUpload(count, counter, blob, completed, start, end, bytesPerChunk);
                            }
                        }
                        xhr
                            .open("POST",
                                "/Video/MultiUpload?id=" + counter.toString() + "&fileName=" + file.name,
                                true);
                        xhr.send(chunk);

                    }
                }                                                                              



        @*$("#btnUpload")
                .click(function (evt) {
                    //evt.preventDefault();
                    ////alert(evt.target.href + "&forceContextSearch=" + $("#forceContextSearch").val());
                    //location.href = evt.target.href + "&forceContextSearch=" + $("#forceContextSearch").val();

                    var blob = file;
                    var bytesPerChunk = @AppValues.FileChunkSz;
                    var size = blob.size;

                    //var start = 0;
                    //var end = bytesPerChunk;
                    //var completed = 0;
                    //var count = size % bytesPerChunk == 0 ? size / bytesPerChunk : Math.floor(size / bytesPerChunk) + 1;
                    //var counter = 0;
                    ////progressBarStart();

                    //multiUpload(count, counter, blob, completed, start, end, bytesPerChunk);




                });*@


        $("#VideoDiv")
            .on("click",
                "#btnUpload",
                function () {

                    uploadFiles();
                    //window.location.href = "/Video/Create";  // trying to refresh current view , in order to see the TempData content.....?!?

                }
            );




        $(function() {
            $('#dropArea')
                .filedrop({
                    url: '@Url.Action("UploadFiles")',
                    //allowedfiletypes: ['image/jpeg', 'image/png', 'image/gif'],
                    //allowedfileextensions: ['.jpg', '.jpeg', '.png', '.gif'],
                    paramname: 'files',
                    maxfiles: 5,
                    maxfilesize: 30, // in MB
                    dragOver: function() {
                        $('#dropArea').addClass('active-drop bgImgLetItGo');
                        //$('#dropArea').addClass('active-drop');
                        //$('#dropText').html("<span style=\"color: fuchsia\" Let it go.... Let it go...></span>");
                        $('#dropText').html("<span style=\"color: white; \">Let it go.... ,  Let it go...</span>");
                    },
                    dragEnter: function() {
                        $('#dropText').html("Drop File(s) Here Please..");
                        //this is useful to reset the AfterAll message if user comes back into dropzone
                    },
                    dragLeave: function() {
                        $('#dropArea').removeClass('active-drop bgImgLetItGo');
                        $('#dropText').html("Drop File(s) Here Please..");
                    },
                    drop: function() {
                        $('#dropArea').removeClass('active-drop bgImgLetItGo');
                        //$('#dropText').html("DROP TRIGGERED");
                    },
                    afterAll: function(e) {
                        $('#dropText').html('file(s) uploaded successfully');
                    },
                    uploadFinished: function(i, file, response, time) {
                        $('#uploadList').append('<li class="list-group-item">' + file.name + '</li>');
                    }
                });
             });
         });
    </script>
} 

DaisyMedia68/DaisyMedia68/Views/Video/PostFile.cshtml
@model DaisyMvc.Models.ViewModels.PostFileVm

@{
    ViewBag.Title = "PostFile";
}

<h2>PostFile</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PostFileVm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Videos")
</div>

DaisyMedia68/DaisyMedia68/Views/Video/Videos.cshtml
@using DaisyMvc.Models
@model DaisyMvc.Models.ViewModels.VideosVm

@{
    ViewBag.Title = "Videos";
}

<div class="jumbotron jumboStyle1 bgImgMinions1" style="padding:20px">

    <h2 style="color:fuchsia">Videos</h2>

    <table class="table">

        @foreach (var item in Model.Videos)
        {
            <tr>
                <td class="col-md-9" style="color: black">
                    @item.Title
                </td>


                <td class="col-md-3">
                    @{             
                        var hh = AppValues.MvcUri + "/Content/UploadedFiles/" + @item.Title;
                        //var hh = AppValues.MvcUriLh + "/Content/UploadedFiles/" + @item.Title;
                    }

                    <a href="@hh" id="fileLink" class="fuchsiaBtn">Open</a>      

                    @*<a href="@hh" id="delFile" class="fuchsiaBtn">Delete</a>*@  

                    @*@Html.ActionLink("Open", "Open", "Video", null, new {@class = "btn btn-md", style = "background-color:fuchsia; color:black"})*@
                    @Html.ActionLink("Delete","DeleteFile", "Video", new {filename=@item.Title}, new {  @class = "WarningBtn"  }) 
                    @*@Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
                </td>


                @*<td class="col-md-3">
                        <video width="100" height="75" controls>
                            <source src="http://localhost:63314/api/MediaFiles/GetVideo?Id=@item.Id" type="video/mp4">
                            <source src="movie.ogg" type="video/ogg">
                            Your browser does not support the video tag.
                        </video>
                    </td>*@
            </tr>
                        }

    </table>
    @Html.ActionLink("Add a file", "Create", "Video", null, new { @class = "fuchsiaBtn"  })
</div>


@*<div class="btn btn-md" style="background-color: orange; color: turquoise; border: turquoise">
    </div>*@
                              
@*@Html.Raw(TempData["getFileResults"])*@